In [1]:
# import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re
import csv
import requests
from bs4 import BeautifulSoup

In [18]:
headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
}

headers

{'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)'}

In [23]:
url = "https://www.magicbricks.com/property-for-rent/residential-real-estate?bedroom=1,2,3&proptype=Multistorey-Apartment,Builder-Floor-Apartment,Penthouse,Studio-Apartment,Service-Apartment,Residential-House,Villa&Locality=Mumbai-Highway,Nagpur-Chal&cityName=Pune"

response = requests.get(url,headers = headers)

soup = BeautifulSoup(response.text, "html.parser")

In [24]:
response

In [27]:
soup.text[:2000]

'\n\n\n\n\n\n\n\n\t\t\n\t\t    \n\t\t       1 BHK Flats for Rent in Mumbai Highway,Nagpur Chal, Pune: 3294+ 1 BHK Rental Apartments in Mumbai Highway,Nagpur Chal\n\t\t    \n\t\t    \n\t\t\n\t\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\xa0BuyPopular ChoicesReady to MoveBudget HomesNew Projects NEWProperty TypesFlats in PuneHouse for sale in PuneVilla in PuneProperty in PunePlots for sale in PuneShop for sale in PuneBudgetExploreLocalities in  PuneProjects in PuneFind an AgentBuying ToolsPropWorthRates & TrendsBuy vs RentTips and GuidesRentPopular ChoicesFurnished HomesProperty TypesFlat for rent in PuneHouse for rent in PuneVilla for rent in PunePG in PuneOffice Space in PuneHostels in PuneRoom for Rent in PuneProperty for Rent in PuneBudgetExploreShare RequirementProperty ServicesRent AgreementSellFor Owner+91 9870 260 930 / Email UsFor Agent & Builder0120-5135525Selling ToolsHome LoansUseful LinksHome LoanHome Loan EMI CalculatorHome Loan Eligibility CalculatorHome Loan Interest RateSign in to get a personalised feed!LoginHome InteriorsMB Advice NewHelpExplore our servicesHome Interior Design ServicesPost Property FreeShortlistLogin to View your shortlisted PropertiesTap on   to shortlistLoginMy ActivityRequested Properties NewView ResponseManage PropertiesMagicDiaryManage AlertsiAdvantageLogin/Sign UpRent ResidentialBuyRentPGCommercialBuyLeaseMumbai HighwayNagpur ChalDoneTop LocalitiesTop Localities DoneBudgetBudget DoneProperty TypeProperty Type DoneBHKBHK DonePosted ByPosted By DoneMore FiltersClear AllView 3294 PropertiesHomeFlats for Rent in PuneFlats for Rent in Mumbai Highway Pune1 BHK Flats for Rent in Mumbai HighwayProperties (3,294) Top AgentsSort by: RelevanceRelevancePrice - Low to HighPrice - High to LowMost RecentRate/sqft - Low to HighRate/sqft - High to Low3294 results | 1 BHK Flats for Rent in Mumbai Highway,Nagpur Chal, PuneAdd Budget for better results 8+ PhotosPosted:   TodayAS K Properties5500+ Buyers Served Know More 3 BHK Flat   for Rent in Pride Valencia, Baner, PunePride ValenciaFur'

In [29]:
title = soup.find_all('h2',attrs ={'class':'mb-srp__card--title'})
for t in title:
    print(t.text)
len(title)

3 BHK Flat   for Rent in Pride Valencia, Baner, Pune
2 BHK Flat   for Rent in Pharande Puneville, Punawale, Pimpri Chinchwad, Pune
2 BHK Flat   for Rent in Uday Emerald Park, Punawale, Pimpri Chinchwad, Pune
2 BHK Flat   for Rent in Pride Valencia, Baner, Pune
3 BHK Flat   for Rent in Pride Purple Park Grandeur, Baner, Pune
2 BHK Flat   for Rent in Godrej Nurture, Mamurdi, Dehu Road, Pune
3 BHK Flat   for Rent in Kohinoor Sapphire 3, Tathawade Pimpri Chinchwad, Pune
3 BHK Flat   for Rent in ABIL Imperial Atria, Baner, Pune
3 BHK Flat   for Rent in The Gateway, Balewadi, Pune
3 BHK Flat   for Rent in Tain Square, Fatima Nagar Wanowrie, Pune
1 BHK Flat   for Rent in Ganga Savera, Fatima Nagar Wanowrie, Pune
3 BHK Flat   for Rent in ANP Atlantis, Balewadi, Pune
2 BHK Flat   for Rent in Majestique Signature Towers, Balewadi, Pune
3 BHK Flat   for Rent in Bhumkar Nagar Wakad, Pune
3 BHK Flat   for Rent in Godrej Green Cove, Mahalunge, Pune
2 BHK Flat   for Rent in Pethkar Siyona, Punawale, Pimpri Chinchwad, Pune
2 BHK Flat   for Rent in Kakkad Madhukosh, Balewadi, Pune
3 BHK Flat   for Rent in Kothrud, Pune
2 BHK Flat   for Rent in Whispering Wind Phase II, Baner, Pune
2 BHK Flat   for Rent in Lohia Jain Vallonia, Bavdhan, Pune
2 BHK Flat   for Rent in Shivsagar City 1, Sun City, Anand Nagar, Pune
1 BHK Flat   for Rent in Sunder Garden, Wadgaon BK, Pune
1 BHK Flat   for Rent in Shivsagar City 1, Sun City, Anand Nagar, Pune
3 BHK Flat   for Rent in Anant Vaibhav, Patil Nagar Bavdhan, Pune
3 BHK Flat   for Rent in Mayura, Kothrud, Pune
3 BHK Flat   for Rent in Prathmesh Elite, Bhusari Colony, Kothrud, Pune
2 BHK Flat   for Rent in Patil Nagar Bavdhan, Pune
2 BHK Flat   for Rent in Perfect 10 Phase4, Laxmi Nagar Balewadi, Pune
1 BHK Flat   for Rent in Madhavbaug Society Shivthirth Nagar, Pune
3 BHK Flat   for Rent in Amanora Gateway Tower 100 , Hadapsar Industrial Estate, Pune

30

In [34]:



Furnish = soup.find_all('div',attrs ={"class":"mb-srp__card__summary--value"})
# mb-srp__card__summary__list
for t in Furnish:
    print(t.text)

Semi-Furnished
3
Family
Immediately
1220 sqft
7 out of 16
East
Garden/Park, Main Road
Pride Valencia
3
3
Semi-Furnished
2
Family
Immediately
865 sqft
13 out of 22
East
Garden/Park, Main Road
Pharande Puneville
2
3
Semi-Furnished
2
Family
Immediately
810 sqft
3 out of 15
East
Garden/Park, Main Road
Uday Emerald Park
2
3
Unfurnished
2
Family
Immediately
1080 sqft
5 out of 10
East
Pool
Pride Valencia
2
2
Furnished
3
Bachelors/Family
Immediately
2200 sqft
Ground out of 19
West
Garden/Park
Pride Purple Park Grandeur
3
3
Furnished
2
Bachelors/Family
Immediately
711 sqft
4 out of 19
North - East
Godrej Nurture
2
Semi-Furnished
3
Bachelors/Family
Immediately
1063 sqft
Upper Basement out of 22
East
Garden/Park, Pool, Main Road
Kohinoor Sapphire 3
3
2
Unfurnished
3
Bachelors/Family
Immediately
1350 sqft
5 out of 11
East
Garden/Park
ABIL Imperial Atria
3
2
Unfurnished
4
Bachelors/Family
Immediately
1500 sqft
5 out of 9
East
Garden/Park
The Gateway
4
2
Unfurnished
3
Family
Immediately
1550 sqft
4 out of 10
East
Main Road
Tain Square
3
2
Unfurnished
1
Family
Immediately
650 sqft
7 out of 7
East
Main Road
Ganga Savera
1
1
Unfurnished
3
Bachelors
Immediately
1327 sqft
11 out of 18
East
Main Road, Garden/Park, Pool
ANP Atlantis
3
2
Semi-Furnished
2
Bachelors
Immediately
860 sqft
7 out of 24
East
Garden/Park, Pool, Main Road
Majestique Signature Towers
Freehold
2
2
Unfurnished
3
Bachelors
Immediately
1200 sqft
9 out of 13
East
Garden/Park, Pool, Main Road
3
3
Semi-Furnished
3
Bachelors
Immediately
1100 sqft
11 out of 22
East
Pool, Garden/Park, Main Road
Godrej Green Cove
3
2
Unfurnished
2
Family
Immediately
855 sqft
6 out of 11
East
Garden/Park
Pethkar Siyona
2
1
Semi-Furnished
2
Bachelors/Family
Immediately
850 sqft
Upper Basement out of 8
Kakkad Madhukosh
2
3
Semi-Furnished
2
Family
Immediately
1000 sqft
1 out of 10
East
Main Road
2
1
Semi-Furnished
2
Bachelors
Immediately
700 sqft
4 out of 6
East
Garden/Park
Whispering Wind Phase II
2
1
Unfurnished
2
Family
Immediately
800 sqft
7 out of 15
Lohia Jain Vallonia
2
2
Furnished
2
Family
Immediately
900 sqft
6 out of 7
East
Main Road
Shivsagar City 1
2
2
Unfurnished
1
Bachelors/Family
Immediately
550 sqft
1 out of 4
North
Garden/Park
Sunder Garden
1
1
Furnished
1
Family
Immediately
500 sqft
5 out of 7
East
Garden/Park
Shivsagar City 1
1
1
Unfurnished
2
Family
From Mar '26
1200 sqft
5 out of 10
East
Garden/Park, Main Road
Anant Vaibhav
2
2
Unfurnished
3
Family
Immediately
955 sqft
10 out of 12
East
Garden/Park
Mayura
3
2
Furnished
3
Bachelors/Family
Immediately
1102 sqft
5 out of 12
East
Garden/Park
Prathmesh Elite
3
2
Unfurnished
2
Family
Immediately
800 sqft
4 out of 8
East
Main Road
2
2
Semi-Furnished
2
Bachelors/Family
Immediately
730 sqft
4 out of 11
East
Main Road
Perfect 10 Phase4
2
1
Semi-Furnished
1
Family
Immediately
550 sqft
3 out of 5
North - East
1
1
Semi-Furnished
3
Bachelors
Immediately
2075 sqft
19 out of 34
South
Pool, Garden/Park
Amanora Gateway Tower 100
3
2

In [52]:

url = "https://www.magicbricks.com/property-for-rent/residential-real-estate?bedroom=1,2,3&proptype=Multistorey-Apartment,Builder-Floor-Apartment,Penthouse,Studio-Apartment,Service-Apartment,Residential-House,Villa&Locality=Mumbai-Highway,Nagpur-Chal&cityName=Pune"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

# cards = soup.find_all('div', class_='mb-srp__card')
cards = soup.find_all('div', class_='mb-srp__card')

with open('clean_magic_bricks_data.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['Title', 'Price_Rs', 'Furnishing', 'Bathrooms', 'Carpet_Area_sqft', 'Floor_No'])

    for card in cards:
        title = card.find('h2', class_='mb-srp__card--title')
        price = card.find('div', class_='mb-srp__card__price--amount')
        summary_items = card.find_all('div', class_='mb-srp__card__summary__list--item')

        furnish, bathroom, carpet_area, floor = '', '', '', ''

        for item in summary_items:
            data_summary = item.get('data-summary', '').strip()
            text_value = item.text.strip()

            if data_summary == 'furnishing':
                # extract actual Furnishing types only
                match = re.search(r'(Furnished|Semi-Furnished|Unfurnished)', text_value, re.IGNORECASE)
                furnish = match.group(1) if match else ''
            elif data_summary == 'bathroom':
                bathroom = re.sub(r'[^0-9]', '', text_value)
            elif data_summary == 'carpet-area':
                carpet_area = re.sub(r'[^0-9.]', '', text_value)
            elif data_summary == 'floor':
                match = re.search(r'(\d+)', text_value)
                floor = match.group(1) if match else ''

        # Clean title and price
        title = title.text.strip() if title else ''
        price = price.text.strip() if price else ''
        price = re.sub(r'[^0-9.]', '', price)

        writer.writerow([title, price, furnish, bathroom, carpet_area, floor])

print("Clean data stored in 'clean_magic_bricks_data.csv' — ready for EDA.")

Clean data stored in 'clean_magic_bricks_data.csv' — ready for EDA.

In [36]:
import pandas as pd

df = pd.read_csv("clean_magic_bricks_data.csv")
df.head()

,Title,Price_Rs,Furnishing,Bathrooms,Carpet_Area_sqft,Floor_No
0,"2 BHK Flat for Rent in Uday Emerald Park, Pu...",20000,Semi-Furnished,2,810.0,3.0
1,"2 BHK Flat for Rent in Pharande Puneville, P...",23500,Semi-Furnished,2,805.0,4.0
2,3 BHK Flat for Rent in Pride Purple Park Xpr...,45000,Unfurnished,3,1192.0,7.0
3,"3 BHK Flat for Rent in Pride Valencia, Baner...",50000,Semi-Furnished,3,1220.0,7.0
4,"2 BHK Flat for Rent in Pride Valencia, Baner...",40000,Unfurnished,2,1080.0,5.0

In [38]:
df

,Title,Price_Rs,Furnishing,Bathrooms,Carpet_Area_sqft,Floor_No
0,"2 BHK Flat for Rent in Uday Emerald Park, Pu...",20000,Semi-Furnished,2,810.0,3.0
1,"2 BHK Flat for Rent in Pharande Puneville, P...",23500,Semi-Furnished,2,805.0,4.0
2,3 BHK Flat for Rent in Pride Purple Park Xpr...,45000,Unfurnished,3,1192.0,7.0
3,"3 BHK Flat for Rent in Pride Valencia, Baner...",50000,Semi-Furnished,3,1220.0,7.0
4,"2 BHK Flat for Rent in Pride Valencia, Baner...",40000,Unfurnished,2,1080.0,5.0
5,"3 BHK Flat for Rent in Nandan Prospera Gold,...",80000,Unfurnished,3,1650.0,9.0
6,3 BHK Flat for Rent in Kalpataru Jade Reside...,82000,Semi-Furnished,4,1750.0,7.0
7,"3 BHK Flat for Rent in Godrej Hillside, Maha...",30000,Semi-Furnished,3,878.0,3.0
8,"2 BHK Flat for Rent in Kohinoor Sapphire 2, ...",24000,Semi-Furnished,2,660.0,3.0
9,"3 BHK Flat for Rent in Kohinoor Sapphire 3, ...",32000,Semi-Furnished,3,1063.0,22.0
10,"3 BHK Flat for Rent in Tain Square, Fatima N...",45000,Unfurnished,3,NaN,6.0
11,"3 BHK Flat for Rent in Kothrud, Pune",49000,Semi-Furnished,2,1000.0,1.0
12,"1 BHK Flat for Rent in Sunder Garden, Wadgao...",17000,Unfurnished,1,550.0,1.0
13,3 BHK Villa for Rent in Sindh Society Pune,3,Unfurnished,4,3800.0,NaN
14,"2 BHK Flat for Rent in Godrej Green Cove, Ma...",30000,Furnished,2,750.0,5.0
15,"3 BHK Flat for Rent in ABIL Imperial Atria, ...",62000,Unfurnished,3,1350.0,5.0
16,"3 BHK Flat for Rent in The Gateway, Balewadi...",55000,Unfurnished,4,1500.0,5.0
17,"1 BHK Flat for Rent in Ganga Savera, Fatima ...",20000,Unfurnished,1,NaN,7.0
18,"3 BHK Flat for Rent in ANP Atlantis, Balewad...",60000,Unfurnished,3,1327.0,11.0
19,2 BHK Flat for Rent in Majestique Signature ...,40600,Semi-Furnished,2,860.0,7.0
20,"3 BHK Flat for Rent in Bhumkar Nagar Wakad, ...",45000,Unfurnished,3,1200.0,9.0
21,"2 BHK Flat for Rent in Pethkar Siyona, Punaw...",25000,Unfurnished,2,855.0,6.0
22,"2 BHK Flat for Rent in Lohia Jain Vallonia, ...",30000,Unfurnished,2,800.0,7.0
23,2 BHK Flat for Rent in Whispering Wind Phase...,35000,Semi-Furnished,2,700.0,4.0
24,"3 BHK Flat for Rent in Tain Square, Fatima N...",46000,Furnished,3,NaN,9.0
25,"2 BHK Flat for Rent in Ganga Paritosh, Sun C...",30000,Semi-Furnished,2,775.0,2.0
26,"3 BHK Flat for Rent in Anant Vaibhav, Patil ...",34000,Unfurnished,2,1200.0,5.0
27,3 BHK Flat for Rent in Paranjape Gloria Gran...,36000,Unfurnished,3,1200.0,8.0
28,"2 BHK Flat for Rent in Perfect 10 Phase4, La...",34000,Semi-Furnished,2,730.0,4.0
29,1 BHK Flat for Rent in Madhavbaug Society Sh...,25000,Semi-Furnished,1,550.0,3.0

In [104]:
# categories = ['Wakad','Kharadi','Hinjawadi','Wagholi','Baner','Hadapsar','Balewadi',Kothrud','Magarpatta City','Viman Nagar']

categories = ['Wakad','Kharadi','Hinjawadi','Wagholi','Baner','Hadapsar','Balewadi','Kothrud','Magarpatta City','Viman Nagar']

locality_data = []
title_data = []
price_data = []
furnish_data = []
bath_data = []
carpet_data = []
floor_data = []

for locality in categories:
    
    for page in range(1,6):   # first 5 pages

        url = f"https://www.magicbricks.com/property-for-rent/residential-real-estate?bedroom=1,2,3&proptype=Multistorey-Apartment,Builder-Floor-Apartment,Penthouse,Studio-Apartment,Service-Apartment,Residential-House,Villa&Locality={locality.replace(' ','%20')}&cityName=Pune&page={page}"

        response = requests.get(url, headers=headers)

        soup = BeautifulSoup(response.text,'html.parser')

        cards = soup.find_all('div',class_='mb-srp__card')

        if len(cards)==0:
            break

        print(locality,"page",page,"cards:",len(cards))

    for card in cards:
        
        title = card.find('h2',class_='mb-srp__card--title')
        title_data.append(title.text.strip() if title else np.nan)
        
        price = card.find('div',class_='mb-srp__card__price--amount')
        price_val = price.text.strip() if price else np.nan
        price_val = re.sub(r'[^0-9.]','',price_val)
        price_data.append(price_val)
        
        summary_items = card.find_all('div',class_='mb-srp__card__summary__list--item')
        
        furnish = bath = carpet = floor = np.nan
        
        for s in summary_items:
            d = s.get('data-summary','').strip()
            t = s.text.strip()
            
            if d=='furnishing':
                m = re.search(r'(Furnished|Semi-Furnished|Unfurnished)',t,re.IGNORECASE)
                furnish = m.group(1) if m else np.nan
                
            elif d=='bathroom':
                bath = re.sub(r'[^0-9]','',t)
                
            elif d=='carpet-area':
                carpet = re.sub(r'[^0-9.]','',t)
                
            elif d=='floor':
                m = re.search(r'(\d+)',t)
                floor = m.group(1) if m else np.nan
        
        locality_data.append(locality)
        furnish_data.append(furnish)
        bath_data.append(bath)
        carpet_data.append(carpet)
        floor_data.append(floor)


df1 = pd.DataFrame({
    'Locality': locality_data,
    'Title': title_data,
    'Price_Rs': price_data,
    'Furnishing': furnish_data,
    'Bathrooms': bath_data,
    'Carpet_Area_sqft': carpet_data,
    'Floor_No': floor_data
})

df1.to_csv('clean_magic_bricks_data_location1.csv',index=False,encoding='utf-8')
print("All localities data saved")

Wakad page 1 cards: 30
Wakad page 2 cards: 30
Wakad page 3 cards: 30
Wakad page 4 cards: 30
Wakad page 5 cards: 30
Kharadi page 1 cards: 30
Kharadi page 2 cards: 30
Kharadi page 3 cards: 30
Kharadi page 4 cards: 30
Kharadi page 5 cards: 30
Hinjawadi page 1 cards: 30
Hinjawadi page 2 cards: 30
Hinjawadi page 3 cards: 30
Hinjawadi page 4 cards: 30
Hinjawadi page 5 cards: 30
Wagholi page 1 cards: 30
Wagholi page 2 cards: 30
Wagholi page 3 cards: 30
Wagholi page 4 cards: 30
Wagholi page 5 cards: 30
Baner page 1 cards: 30
Baner page 2 cards: 30
Baner page 3 cards: 30
Baner page 4 cards: 30
Baner page 5 cards: 30
Hadapsar page 1 cards: 30
Hadapsar page 2 cards: 30
Hadapsar page 3 cards: 30
Hadapsar page 4 cards: 30
Hadapsar page 5 cards: 30
Balewadi page 1 cards: 30
Balewadi page 2 cards: 30
Balewadi page 3 cards: 30
Balewadi page 4 cards: 30
Balewadi page 5 cards: 30
Kothrud page 1 cards: 30
Kothrud page 2 cards: 30
Kothrud page 3 cards: 30
Kothrud page 4 cards: 30
Kothrud page 5 cards: 30
Magarpatta City page 1 cards: 30
Magarpatta City page 2 cards: 30
Magarpatta City page 3 cards: 30
Magarpatta City page 4 cards: 30
Magarpatta City page 5 cards: 30
Viman Nagar page 1 cards: 30
Viman Nagar page 2 cards: 30
Viman Nagar page 3 cards: 30
Viman Nagar page 4 cards: 30
Viman Nagar page 5 cards: 30
All localities data saved

In [108]:
import os
os.listdir()

[' Cleaning Copy.ipynb',
 '.ipynb_checkpoints',
 'Analysis.ipynb',
 'cleaning.ipynb',
 'clean_magic_bricks_data.csv',
 'clean_magic_bricks_data_location1.csv',
 'clean_magic_bricks_data_location1_parsed.csv',
 'clean_real_estate_mumbai.csv',
 'clean_real_estate_mumbai_parsed.csv',
 'csv',
 'EDA.ipynb',
 'Magic Bricks.ipynb',
 'magic copy',
 'magic copy.ipynb',
 'pune_mumbai_combined.csv',
 'pune_mumbai_combined2.csv']

In [110]:
pd.read_csv("clean_magic_bricks_data_location1.csv").shape

(300, 7)

In [115]:
df1.shape

(300, 7)

In [117]:
df1

,Locality,Title,Price_Rs,Furnishing,Bathrooms,Carpet_Area_sqft,Floor_No
0,Wakad,"3 BHK Flat for Rent in Wakad, Pune",60000,Furnished,3,1086,7
1,Wakad,"2 BHK Flat for Rent in Ganesh Imperia, Wakad...",19500,Semi-Furnished,2,NaN,2
2,Wakad,"2 BHK Flat for Rent in Paranjape Broadway, W...",27000,Furnished,2,NaN,5
3,Wakad,"3 BHK Flat for Rent in Paramount Altissimo, ...",42000,Semi-Furnished,3,NaN,8
4,Wakad,"2 BHK Flat for Rent in Wakad, Pune",38000,Furnished,2,NaN,11
...,...,...,...,...,...,...,...
295,Viman Nagar,"2 BHK Flat for Rent in Viman Nagar Central, ...",40000,Semi-Furnished,2,829,3
296,Viman Nagar,"1 BHK Flat for Rent in Konark Nagar, Viman N...",29000,Furnished,1,580,2
297,Viman Nagar,"3 BHK Flat for Rent in Shubh Gateway, Viman ...",1.3,Furnished,3,2000,9
298,Viman Nagar,"3 BHK Flat for Rent in Sky View Apartment, V...",75000,Furnished,3,1200,5
299,Viman Nagar,"2 BHK Flat for Rent in Lunkad Colonnade I, V...",40000,Furnished,2,NaN,6

## Here seperated the columns from title

In [120]:
import pandas as pd
import numpy as np
import re

df1 = pd.read_csv("clean_magic_bricks_data_location1.csv")

# Clean title
df1['Title'] = df1['Title'].astype(str).str.replace(r'\s+', ' ', regex=True).str.strip()

# Extract fields
df1['BHK'] = df1['Title'].str.extract(r'(\d+)\s*(?:BHK|RK)', expand=False)
df1['BHK'] = pd.to_numeric(df1['BHK'], errors='coerce').astype('Int64')

df1['Property_Type'] = df1['Title'].str.extract(r'(?:\d+\s*(?:BHK|RK)\s*)(.*?)\s*for\b', expand=False)
df1['Listing_Type']  = df1['Title'].str.extract(r'\bfor\s+([A-Za-z]+)', expand=False)



# Replace string 'nan' with NaN properly
df1 = df1.apply(lambda s: s.where(s.ne('nan'), np.nan))

df1.to_csv("clean_magic_bricks_data_location1_parsed.csv", index=False, encoding="utf-8")
print("Done! BHK cleaned and saved.")

Done! BHK cleaned and saved.

In [122]:
df1.shape

(300, 10)

In [126]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re

# Mumbai Areas
categories = [
    'Andheri West','Chembur','Mulund West','Worli','Kandivali East',
    'Goregaon West','Malad West','Powai','Borivali East','Goregaon East'
]

locality_data = []
title_data = []
price_data = []
furnish_data = []
bath_data = []
carpet_data = []
floor_data = []

for locality in categories:
    
    url = f"https://www.magicbricks.com/property-for-rent/residential-real-estate?bedroom=&proptype=Multistorey-Apartment,Builder-Floor-Apartment,Penthouse,Studio-Apartment,Service-Apartment&Locality={locality.replace(' ','%20')}&cityName=Mumbai"
    
    headers = {
        "User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
    }
    
    response = requests.get(url, headers=headers)
    
    if response.status_code == 403:
        print("403 Error found")
        break
    
    print(response.status_code,"Scraping:",locality)
    soup = BeautifulSoup(response.text,'html.parser')
    
    cards = soup.find_all('div',class_='mb-srp__card')
    
    for card in cards:
        
        title = card.find('h2',class_='mb-srp__card--title')
        title_data.append(title.text.strip() if title else np.nan)
        
        price = card.find('div',class_='mb-srp__card__price--amount')
        price_val = price.text.strip() if price else np.nan
        price_val = re.sub(r'[^0-9.]','',price_val)
        price_data.append(price_val)
        
        summary_items = card.find_all('div',class_='mb-srp__card__summary__list--item')
        
        furnish = bath = carpet = floor = np.nan
        
        for s in summary_items:
            d = s.get('data-summary','').strip()
            t = s.text.strip()
            
            if d=='furnishing':
                m = re.search(r'(Furnished|Semi-Furnished|Unfurnished)',t,re.IGNORECASE)
                furnish = m.group(1) if m else np.nan
                
            elif d=='bathroom':
                bath = re.sub(r'[^0-9]','',t)
                
            elif d=='carpet-area':
                carpet = re.sub(r'[^0-9.]','',t)
                
            elif d=='floor':
                m = re.search(r'(\d+)',t)
                floor = m.group(1) if m else np.nan
        
        locality_data.append(locality)
        furnish_data.append(furnish)
        bath_data.append(bath)
        carpet_data.append(carpet)
        floor_data.append(floor)


df = pd.DataFrame({
    'Locality': locality_data,
    'Title': title_data,
    'Price_Rs': price_data,
    'Furnishing': furnish_data,
    'Bathrooms': bath_data,
    'Carpet_Area_sqft': carpet_data,
    'Floor_No': floor_data
})

df.to_csv('clean_real_estate_mumbai.csv',index=False,encoding='utf-8')
print("All Mumbai localities data saved")

200 Scraping: Andheri West
200 Scraping: Chembur
200 Scraping: Mulund West
200 Scraping: Worli
200 Scraping: Kandivali East
200 Scraping: Goregaon West
200 Scraping: Malad West
200 Scraping: Powai
200 Scraping: Borivali East
200 Scraping: Goregaon East
All Mumbai localities data saved

In [124]:
df

,Title,Price_Rs,Furnishing,Bathrooms,Carpet_Area_sqft,Floor_No
0,"2 BHK Flat for Rent in Uday Emerald Park, Pu...",20000,Semi-Furnished,2,810.0,3.0
1,"2 BHK Flat for Rent in Pharande Puneville, P...",23500,Semi-Furnished,2,805.0,4.0
2,3 BHK Flat for Rent in Pride Purple Park Xpr...,45000,Unfurnished,3,1192.0,7.0
3,"3 BHK Flat for Rent in Pride Valencia, Baner...",50000,Semi-Furnished,3,1220.0,7.0
4,"2 BHK Flat for Rent in Pride Valencia, Baner...",40000,Unfurnished,2,1080.0,5.0
5,"3 BHK Flat for Rent in Nandan Prospera Gold,...",80000,Unfurnished,3,1650.0,9.0
6,3 BHK Flat for Rent in Kalpataru Jade Reside...,82000,Semi-Furnished,4,1750.0,7.0
7,"3 BHK Flat for Rent in Godrej Hillside, Maha...",30000,Semi-Furnished,3,878.0,3.0
8,"2 BHK Flat for Rent in Kohinoor Sapphire 2, ...",24000,Semi-Furnished,2,660.0,3.0
9,"3 BHK Flat for Rent in Kohinoor Sapphire 3, ...",32000,Semi-Furnished,3,1063.0,22.0
10,"3 BHK Flat for Rent in Tain Square, Fatima N...",45000,Unfurnished,3,NaN,6.0
11,"3 BHK Flat for Rent in Kothrud, Pune",49000,Semi-Furnished,2,1000.0,1.0
12,"1 BHK Flat for Rent in Sunder Garden, Wadgao...",17000,Unfurnished,1,550.0,1.0
13,3 BHK Villa for Rent in Sindh Society Pune,3,Unfurnished,4,3800.0,NaN
14,"2 BHK Flat for Rent in Godrej Green Cove, Ma...",30000,Furnished,2,750.0,5.0
15,"3 BHK Flat for Rent in ABIL Imperial Atria, ...",62000,Unfurnished,3,1350.0,5.0
16,"3 BHK Flat for Rent in The Gateway, Balewadi...",55000,Unfurnished,4,1500.0,5.0
17,"1 BHK Flat for Rent in Ganga Savera, Fatima ...",20000,Unfurnished,1,NaN,7.0
18,"3 BHK Flat for Rent in ANP Atlantis, Balewad...",60000,Unfurnished,3,1327.0,11.0
19,2 BHK Flat for Rent in Majestique Signature ...,40600,Semi-Furnished,2,860.0,7.0
20,"3 BHK Flat for Rent in Bhumkar Nagar Wakad, ...",45000,Unfurnished,3,1200.0,9.0
21,"2 BHK Flat for Rent in Pethkar Siyona, Punaw...",25000,Unfurnished,2,855.0,6.0
22,"2 BHK Flat for Rent in Lohia Jain Vallonia, ...",30000,Unfurnished,2,800.0,7.0
23,2 BHK Flat for Rent in Whispering Wind Phase...,35000,Semi-Furnished,2,700.0,4.0
24,"3 BHK Flat for Rent in Tain Square, Fatima N...",46000,Furnished,3,NaN,9.0
25,"2 BHK Flat for Rent in Ganga Paritosh, Sun C...",30000,Semi-Furnished,2,775.0,2.0
26,"3 BHK Flat for Rent in Anant Vaibhav, Patil ...",34000,Unfurnished,2,1200.0,5.0
27,3 BHK Flat for Rent in Paranjape Gloria Gran...,36000,Unfurnished,3,1200.0,8.0
28,"2 BHK Flat for Rent in Perfect 10 Phase4, La...",34000,Semi-Furnished,2,730.0,4.0
29,1 BHK Flat for Rent in Madhavbaug Society Sh...,25000,Semi-Furnished,1,550.0,3.0

# Extracted the columns of Title in Mumbai

In [85]:
# 1) Load Nashik scraped csv
df = pd.read_csv("clean_real_estate_mumbai.csv")

# 2) Clean title
df['Title'] = df['Title'].astype(str).str.replace(r'\s+', ' ', regex=True).str.strip()

# 3) Extract BHK number only
df['BHK'] = df['Title'].str.extract(r'(\d+)\s*(?:BHK|RK)', expand=False).astype('Int64')

# 4) Extract Property type (Flat / Studio Apartment etc.)
df['Property_Type'] = df['Title'].str.extract(r'(?:\d+\s*(?:BHK|RK)\s*)(.*?)\s*for', expand=False)

# 5) Extract listing type (Rent or Sale)
df['Listing_Type']  = df['Title'].str.extract(r'\bfor\s+([A-Za-z]+)', expand=False)

# 6) Extract everything after "in "
df['location_part'] = df['Title'].str.extract(r'\bin\s*(.*)', expand=False)

# 7) City = last part
df['City'] = df['location_part'].str.split(',').str[-1].str.strip()

# 8) Locality = second last part
df['Locality'] = df['location_part'].str.split(',').str[-2].str.strip()

# 9) Society = everything before last two comma parts
df['Society'] = df['location_part'].apply(
    lambda x: ','.join(x.split(',')[:-2]).strip() if isinstance(x, str) and x.count(',') >= 2 else np.nan
)

# 10) Convert numeric columns
df['Price_Rs'] = pd.to_numeric(df['Price_Rs'], errors='coerce')
df['Bathrooms'] = pd.to_numeric(df['Bathrooms'], errors='coerce').astype('Int64')
df['Carpet_Area_sqft'] = pd.to_numeric(df['Carpet_Area_sqft'], errors='coerce').astype('Int64')
df['Floor_No'] = pd.to_numeric(df['Floor_No'], errors='coerce').astype('Int64')

# 11) Remove helper column
df = df.drop(columns=['location_part'])

# 12) Save
df.to_csv("clean_real_estate_mumbai_parsed.csv", index=False)
print("Mumbai cleaned & extracted successfully!")

Mumbai cleaned & extracted successfully!

In [140]:
df

,Locality,Title,Price_Rs,Furnishing,Bathrooms,Carpet_Area_sqft,Floor_No
0,Andheri West,"3 BHK Flat for Rent in Adani Western Heights,...",2,Furnished,3,1100,10
1,Andheri West,"3 BHK Flat for Rent in Oberoi Springs, Andher...",1.5,Furnished,2,1000,NaN
2,Andheri West,"3 BHK Flat for Rent in HDIL Metropolis, Andhe...",1.5,Semi-Furnished,3,1322,19
3,Andheri West,"3 BHK Flat for Rent in Oberoi Springs, Andher...",1.7,Furnished,2,847,16
4,Andheri West,"2 BHK Flat for Rent in Evershine Embassy, And...",67000,Unfurnished,2,650,5
...,...,...,...,...,...,...,...
295,Goregaon East,"2 BHK Flat for Rent in New Mahada Colony, Gor...",45000,Semi-Furnished,2,550,4
296,Goregaon East,"5 BHK Flat for Rent in Oberoi Woods, Goregaon...",3.3,Semi-Furnished,4,1966,12
297,Goregaon East,"4 BHK Flat for Rent in Oberoi Esquire, Gorega...",3.9,Semi-Furnished,3,2291,40
298,Goregaon East,"2 BHK Flat for Rent in IM Applaud 38, Goregao...",75000,Unfurnished,2,761,31
299,Goregaon East,"4 BHK Flat for Rent in Meenaxi Apartments, Go...",1.4,Furnished,4,1600,7

# Combining the both tables

In [132]:
pune = pd.read_csv("clean_magic_bricks_data_location1_parsed.csv")
mumbai = pd.read_csv("clean_real_estate_mumbai_parsed.csv")

In [136]:
combined = pd.concat([pune, mumbai], ignore_index=True)

In [138]:
combined.to_csv("pune_mumbai_combined.csv", index=False)
print("Combined file saved: pune_mumbai_combined.csv")

Combined file saved: pune_mumbai_combined.csv

In [150]:
df['Price_Rs'] = pd.to_numeric(df['Price_Rs'], errors='coerce')
df['Carpet_Area_sqft'] = pd.to_numeric(df['Carpet_Area_sqft'], errors='coerce')

In [152]:
df['Price_per_sqft'] = df['Price_Rs'] / df['Carpet_Area_sqft']
df['Price_per_sqft'] = df['Price_per_sqft'].round(2)

In [154]:
df.to_csv("pune_mumbai_combined.csv", index=False)

In [156]:
df

,Locality,Title,Price_Rs,Furnishing,Bathrooms,Carpet_Area_sqft,Floor_No,BHK,Property_Type,Listing_Type,City,Society,Price_per_sqft
0,Wakad,"3 BHK Flat for Rent in Wakad, Pune",60000.0,Furnished,3.0,1086.0,7.0,3,Flat,Rent,NaN,NaN,55.25
1,Wakad,"2 BHK Flat for Rent in Ganesh Imperia, Wakad, ...",19500.0,Semi-Furnished,2.0,NaN,2.0,2,Flat,Rent,NaN,NaN,NaN
2,Wakad,"2 BHK Flat for Rent in Paranjape Broadway, Wak...",27000.0,Furnished,2.0,NaN,5.0,2,Flat,Rent,NaN,NaN,NaN
3,Wakad,"3 BHK Flat for Rent in Paramount Altissimo, Wa...",42000.0,Semi-Furnished,3.0,NaN,8.0,3,Flat,Rent,NaN,NaN,NaN
4,Wakad,"2 BHK Flat for Rent in Wakad, Pune",38000.0,Furnished,2.0,NaN,11.0,2,Flat,Rent,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,Goregaon East,"5 BHK Flat for Rent in Oberoi Woods, Goregaon ...",3.0,Semi-Furnished,3.0,1900.0,19.0,5,Flat,Rent,Mumbai,Oberoi Woods,0.00
596,Goregaon East,"5 BHK Flat for Rent in Oberoi Woods, Goregaon ...",3.3,Semi-Furnished,4.0,1966.0,12.0,5,Flat,Rent,Mumbai,Oberoi Woods,0.00
597,Goregaon East,"3 BHK Flat for Rent in Oberoi Exquisite II, Go...",1.9,Semi-Furnished,3.0,1245.0,27.0,3,Flat,Rent,Mumbai,Oberoi Exquisite II,0.00
598,Goregaon East,"3 BHK Flat for Rent in Oberoi Exquisite, Goreg...",1.8,Semi-Furnished,3.0,1041.0,28.0,3,Flat,Rent,Mumbai,Oberoi Exquisite,0.00
599,Goregaon East,"4 BHK Flat for Rent in Meenaxi Apartments, Gor...",1.4,Furnished,4.0,1600.0,7.0,4,Flat,Rent,Mumbai,Meenaxi Apartments,0.00

In [158]:
import pandas as pd

df = pd.read_csv("pune_mumbai_combined.csv")
df

,Locality,Title,Price_Rs,Furnishing,Bathrooms,Carpet_Area_sqft,Floor_No,BHK,Property_Type,Listing_Type,City,Society,Price_per_sqft
0,Wakad,"3 BHK Flat for Rent in Wakad, Pune",60000.0,Furnished,3.0,1086.0,7.0,3,Flat,Rent,NaN,NaN,55.25
1,Wakad,"2 BHK Flat for Rent in Ganesh Imperia, Wakad, ...",19500.0,Semi-Furnished,2.0,NaN,2.0,2,Flat,Rent,NaN,NaN,NaN
2,Wakad,"2 BHK Flat for Rent in Paranjape Broadway, Wak...",27000.0,Furnished,2.0,NaN,5.0,2,Flat,Rent,NaN,NaN,NaN
3,Wakad,"3 BHK Flat for Rent in Paramount Altissimo, Wa...",42000.0,Semi-Furnished,3.0,NaN,8.0,3,Flat,Rent,NaN,NaN,NaN
4,Wakad,"2 BHK Flat for Rent in Wakad, Pune",38000.0,Furnished,2.0,NaN,11.0,2,Flat,Rent,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,Goregaon East,"5 BHK Flat for Rent in Oberoi Woods, Goregaon ...",3.0,Semi-Furnished,3.0,1900.0,19.0,5,Flat,Rent,Mumbai,Oberoi Woods,0.00
596,Goregaon East,"5 BHK Flat for Rent in Oberoi Woods, Goregaon ...",3.3,Semi-Furnished,4.0,1966.0,12.0,5,Flat,Rent,Mumbai,Oberoi Woods,0.00
597,Goregaon East,"3 BHK Flat for Rent in Oberoi Exquisite II, Go...",1.9,Semi-Furnished,3.0,1245.0,27.0,3,Flat,Rent,Mumbai,Oberoi Exquisite II,0.00
598,Goregaon East,"3 BHK Flat for Rent in Oberoi Exquisite, Goreg...",1.8,Semi-Furnished,3.0,1041.0,28.0,3,Flat,Rent,Mumbai,Oberoi Exquisite,0.00
599,Goregaon East,"4 BHK Flat for Rent in Meenaxi Apartments, Gor...",1.4,Furnished,4.0,1600.0,7.0,4,Flat,Rent,Mumbai,Meenaxi Apartments,0.00

In [160]:
df1 = pd.read_csv("pune_mumbai_combined.csv")
print(df1.shape)

(600, 13)